#! /bin/bash
#
# Küsib kasutaja andmeid ja tervitab kasutajat
echo -n "Sisesta oma ees- ja perenimi:" 
read eesnimi perenimi #loeb kirjutatud väärtuse
echo " Tere, $eesnimi $perenimi!" #prindib välja kirjutatud väärtuse
#
#skripti lõpp

